### PR TITLE
Defining Models and their entity relationships 

### PR DESCRIPTION
**Pull request by sydneymainga**
Kindly review and particularly on entity relations if things were taken care of correctly

### CODE REVIEW

**Review by Hudson-obai — COMMENTED** [review]
Hey Sydney, why didn't you let JPA do the mapping for you instead of creating the pivot tables yourself?

**Comment by sydneymainga** [comment]
> Hey Sydney, why didn't you let JPA do the mapping for you instead of creating the pivot tables yourself? 

That was my first approach but after doing some research I think I used JPA for the mapping

**Review by Hudson-obai — COMMENTED** [review]
Can you explain why you are using Users as a plural? I would rather name it User

**Comment by sydneymainga** [comment]
> Can you explain why you are using Users as a plural? I would rather name it User 
> 

Okay . I will change that.....should I maintain singularity in naming the entities?

**Review by Hudson-obai — APPROVED** [review]

**Pull request merged**
